wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1655996760
    t:
      1:
      - 1
      - 41
      - 55
      4: 3.7.0
      5: 0.12.19
      8:
      - 5
